# Generated by Django 5.1.7 on 2025-03-29 14:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISINCode', models.CharField(max_length=12, unique=True, verbose_name='ISIN Code')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('trading_symbol', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Trading Symbol')),
                ('industry', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Automobiles & Accessories', 'Automobiles & Accessories'), ('Banking', 'Banking'), ('Commercial & Services', 'Commercial & Services'), ('Construction & Allied', 'Construction & Allied'), ('Energy & Petroleum', 'Energy & Petroleum'), ('Insurance', 'Insurance'), ('Investment', 'Investment'), ('Investment Services', 'Investment Services'), ('Manufacturing & Allied', 'Manufacturing & Allied'), ('Telecommunication & Technology', 'Telecommunication & Technology'), ('Real Estate Investment Trust', 'Real Estate Investment Trust'), ('Exchange Traded Fund', 'Exchange Traded Fund')], default='Banking', max_length=50, verbose_name='Industry')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Company Logo')),
            ],
            options={
                'verbose_name': 'Listed Company',
                'verbose_name_plural': 'Listed Companies',
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_wallet', models.CharField(max_length=255, unique=True, verbose_name='Investor Wallet Address')),
                ('investor_name', models.CharField(max_length=255, verbose_name='Investor Name')),
                ('id_passport', models.CharField(max_length=50, unique=True, verbose_name='ID/Passport Number')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Investor',
                'verbose_name_plural': 'Investors',
            },
        ),
        migrations.CreateModel(
            name='ListedCompanyBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_name', models.CharField(max_length=255, unique=True, verbose_name='Token Name')),
                ('token_symbol', models.CharField(max_length=10, unique=True, verbose_name='Token Symbol')),
                ('initial_supply', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Initial Supply')),
                ('treasure_account', models.CharField(max_length=255, verbose_name='Treasury Account')),
                ('max_supply', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Max Supply')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('maturity_date', models.DateField(verbose_name='Maturity Date')),
                ('coupon', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Coupon Rate (%)')),
                ('coupon_frequency', models.CharField(choices=[('Annual', 'Annual'), ('Semi-Annual', 'Semi-Annual'), ('Quarterly', 'Quarterly'), ('Monthly', 'Monthly')], max_length=50, verbose_name='Coupon Frequency')),
                ('bond_purpose', models.TextField(verbose_name='Bond Purpose')),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Outstanding Amount')),
                ('ISINCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to='bonds.listedcompany', to_field='ISINCode', verbose_name='ISIN Code')),
            ],
            options={
                'verbose_name': 'Listed Company Bond',
                'verbose_name_plural': 'Listed Company Bonds',
            },
        ),
        migrations.CreateModel(
            name='InvestorBondBid',
            fields=[
                ('bid_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Bid ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Bid Amount')),
                ('bid_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Bid Status')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='bonds.investor', verbose_name='Investor')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='bonds.listedcompanybond', verbose_name='Token')),
            ],
            options={
                'verbose_name': 'Investor Bond Bid',
                'verbose_name_plural': 'Investor Bond Bids',
            },
        ),
    ]
