# Generated by Django 5.1.7 on 2025-03-28 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISINCode', models.CharField(max_length=20, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('trading_symbol', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_wallet', models.CharField(max_length=255, unique=True)),
                ('investor_name', models.CharField(max_length=255)),
                ('id_passport', models.CharField(max_length=50, unique=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListedCompanyBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_name', models.CharField(max_length=255, unique=True)),
                ('token_symbol', models.CharField(max_length=10, unique=True)),
                ('initial_supply', models.DecimalField(decimal_places=2, max_digits=20)),
                ('treasure_account', models.CharField(max_length=255)),
                ('max_supply', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('issue_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('coupon', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coupon_frequency', models.CharField(choices=[('Annual', 'Annual'), ('Semi-Annual', 'Semi-Annual'), ('Quarterly', 'Quarterly'), ('Monthly', 'Monthly')], max_length=50)),
                ('bond_purpose', models.TextField()),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ISINCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonds.listedcompany', to_field='ISINCode')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorBondBid',
            fields=[
                ('bid_id', models.AutoField(primary_key=True, serialize=False)),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('bid_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonds.investor')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonds.listedcompanybond')),
            ],
        ),
    ]
