# Generated by Django 5.1.7 on 2025-03-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='private_key',
            field=models.TextField(blank=True, null=True, verbose_name='Hedera Private Key (Store Securely)'),
        ),
        migrations.AddField(
            model_name='investor',
            name='public_key',
            field=models.TextField(blank=True, null=True, verbose_name='Hedera Public Key'),
        ),
    ]
