# Generated by Django 5.1.7 on 2025-03-31 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0002_investor_private_key_investor_public_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listedcompanybond',
            old_name='treasure_account',
            new_name='treasury_account',
        ),
        migrations.AlterField(
            model_name='investor',
            name='id_passport',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='ID/Passport Number'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='investor_wallet',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Investor Wallet Address'),
        ),
        migrations.AlterField(
            model_name='investorbondbid',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bid Amount'),
        ),
        migrations.AlterField(
            model_name='listedcompany',
            name='ISINCode',
            field=models.CharField(db_index=True, max_length=12, unique=True, verbose_name='ISIN Code'),
        ),
        migrations.AlterField(
            model_name='listedcompanybond',
            name='initial_supply',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Initial Supply'),
        ),
        migrations.AlterField(
            model_name='listedcompanybond',
            name='outstanding_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Outstanding Amount'),
        ),
    ]
