# Generated by Django 5.1.7 on 2025-03-28 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0002_listedcompany_company_logo_listedcompany_industry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investorbondbid',
            old_name='investor',
            new_name='investor_wallet',
        ),
    ]
