# Generated by Django 5.1.7 on 2025-03-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0003_rename_treasure_account_listedcompanybond_treasury_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='private_key',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Hedera Private Key (Store Securely)'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='public_key',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Hedera Public Key'),
        ),
    ]
