# Generated by Django 5.1.7 on 2025-03-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0004_alter_investor_private_key_alter_investor_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedcompanybond',
            name='token_id',
            field=models.CharField(max_length=15, null=True, verbose_name='Token ID'),
        ),
    ]
